export const ERROR_CODES = {
  // Authentication & Authorization
  EMAIL_NOT_FOUND: 'AUTH_000',
  INVALID_CREDENTIALS: 'AUTH_001',
  INVALID_USERNAME: 'AUTH_002',
  INVALID_PASSWORD: 'AUTH_003',
  TOKEN_EXPIRED: 'AUTH_004',
  TOKEN_INVALID: 'AUTH_005',
  INSUFFICIENT_PERMISSIONS: 'AUTH_006',
  ACCOUNT_LOCKED: 'AUTH_007',
  UNAUTHORIZED: 'AUTH_008',
  INVALID_ACCESS_TOKEN: 'AUTH_009',
  INVALID_REFRESH_TOKEN: 'AUTH_010',
  USER_BANNED: 'AUTH_011',
  NOT_LOGGED_IN_FOR_FIRST_TIME: 'AUTH_012',
  INVALID_OLD_PASSWORD: 'AUTH_013',

  // User Management
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_INACTIVE: 'USER_003',
  EMAIL_ALREADY_EXISTS: 'USER_004',
  INVALID_USER_DATA: 'USER_005',
  USER_STATS_NOT_FOUND: 'USER_006',
  SUBSCRIPTION_NOT_FOUND: 'USER_007',
  USER_OVER_STORAGE_LIMIT: 'USER_008',
  UPDATE_AVATAR_FAILED: 'USER_009',
  UPDATE_USER_FAILED: 'USER_010',
  PHONE_ALREADY_EXISTS: 'USER_011',
  USERNAME_ALREADY_EXISTS: 'USER_012',
  ADDRESS_NOT_FOUND: 'USER_013',
  CREATE_ADDRESS_FAILED: 'USER_014',
  UPDATE_ADDRESS_FAILED: 'USER_015',
  DELETE_ADDRESS_FAILED: 'USER_016',
  ADDRESS_NOT_OWNED: 'USER_017',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_001',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_002',
  CATEGORY_CANNOT_BE_OWN_PARENT: 'CATEGORY_003',
  PARENT_CATEGORY_NOT_FOUND: 'CATEGORY_004',
  DELETE_CATEGORY_HAS_CHILDREN: 'CATEGORY_005',
  DELETE_CATEGORY_HAS_PRODUCTS: 'CATEGORY_006',

  // Brand
  BRAND_NOT_FOUND: 'BRAND_001',
  BRAND_ALREADY_EXISTS: 'BRAND_002',
  DELETE_BRAND_HAS_PRODUCTS: 'BRAND_003',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_001',
  PRODUCT_SKU_EXISTS: 'PRODUCT_002',
  PRODUCT_VARIANT_SKU_EXISTS: 'PRODUCT_003',
  PRODUCT_HAS_ORDERS: 'PRODUCT_004',
  PRODUCT_IMAGE_NOT_FOUND: 'PRODUCT_005',
  PRODUCT_IMAGE_LIMIT_EXCEEDED: 'PRODUCT_006',
  PRODUCT_VIDEO_NOT_FOUND: 'PRODUCT_007',
  PRODUCT_VARIANT_NOT_FOUND: 'PRODUCT_008',
  PRODUCT_VARIANT_HAS_ORDERS: 'PRODUCT_009',

  // Review
  REVIEW_NOT_FOUND: 'REVIEW_001',
  REVIEW_ALREADY_EXISTS: 'REVIEW_002',
  REVIEW_IMAGE_NOT_FOUND: 'REVIEW_003',
  REVIEW_IMAGE_LIMIT_EXCEEDED: 'REVIEW_004',
  REVIEW_NOT_OWNED: 'REVIEW_005',

  // Banner
  BANNER_GROUP_NOT_FOUND: 'BANNER_001',
  BANNER_GROUP_SLUG_EXISTS: 'BANNER_002',
  BANNER_NOT_FOUND: 'BANNER_003',
  NO_ACTIVE_BANNER_GROUP: 'BANNER_004',

  // Storage & Media
  DOWNLOAD_SESSION_NOT_FOUND: 'STORAGE_001',
  DOWNLOAD_SESSION_NOT_PENDING: 'STORAGE_002',
  DOWNLOAD_SESSION_NOT_ALLOWED: 'STORAGE_003',
  DOWNLOAD_SESSION_NOT_COMPLETED: 'STORAGE_004',
  DOWNLOAD_SESSION_NOT_ALLOWED_TO_COMPLETE: 'STORAGE_005',
  DOWNLOAD_SESSION_ALREADY_COMPLETED: 'STORAGE_006',
  FOLDER_ALREADY_EXISTS: 'STORAGE_007',
  FOLDER_NOT_FOUND: 'STORAGE_008',
  FOLDER_NOT_ALLOWED_TO_UPDATE: 'STORAGE_009',
  MEDIA_NOT_FOUND: 'STORAGE_010',
  UPLOAD_FAILED: 'STORAGE_011',
  FILE_TYPE_NOT_SUPPORTED: 'STORAGE_012',
  IMAGE_TOO_LARGE: 'STORAGE_013',
  VIDEO_TOO_LARGE: 'STORAGE_014',
  DELETE_FILE_FAILED: 'STORAGE_015',

  // Referral
  REFERRAL_NOT_FOUND: 'REFERRAL_001',
  REFERRAL_USER_ALREADY_EXISTS: 'REFERRAL_002',
  REFERRAL_STATS_NOT_FOUND: 'REFERRAL_003',

  // Mail
  MAIL_CONFIGURATION_ERROR: 'MAIL_001',
  MAIL_SEND_FAILED: 'MAIL_002',
  MAIL_TEMPLATE_NOT_FOUND: 'MAIL_003',
  MAIL_INVALID_EMAIL: 'MAIL_004',
  MAIL_SMTP_CONNECTION_FAILED: 'MAIL_005',

  // Business Logic
  INVALID_OPERATION: 'BIZ_001',
  RESOURCE_NOT_FOUND: 'BIZ_002',
  OPERATION_NOT_ALLOWED: 'BIZ_003',
  BUSINESS_RULE_VIOLATION: 'BIZ_004',
  INSUFFICIENT_BALANCE: 'BIZ_005',
  NOT_ALLOWED_TO_ACCESS_FILE: 'BIZ_006',

  // Validation
  VALIDATION_FAILED: 'VAL_001',
  INVALID_INPUT_FORMAT: 'VAL_002',
  REQUIRED_FIELD_MISSING: 'VAL_003',
  INVALID_FILE_TYPE: 'VAL_004',
  FILE_TOO_LARGE: 'VAL_005',

  // System Errors
  DATABASE_ERROR: 'SYS_001',
  EXTERNAL_SERVICE_ERROR: 'SYS_002',
  RATE_LIMIT_EXCEEDED: 'SYS_003',
  SERVICE_UNAVAILABLE: 'SYS_004',
  INTERNAL_SERVER_ERROR: 'SYS_999',
  NOT_ALLOWED_BY_CORS: 'SYS_005',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
